apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: swisnap-agent-ds
  namespace: kube-system
  labels:
    daemon: swisnap-agent-ds
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: swisnap-agent-ds
      labels:
        daemon: swisnap-agent-ds
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: swisnap-agent-ds
        image: 'solarwinds/solarwinds-snap-agent-docker:latest'
        imagePullPolicy: Always
        env:
          - name: APPOPTICS_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: APPOPTICS_TOKEN
            valueFrom:
              configMapKeyRef:
                name: appoptics-token
                key: APPOPTICS_TOKEN
        envFrom:
          - configMapRef:
              name: swisnap-agent-ds-configmap
        volumeMounts:
          - name: docker-sock
            mountPath: /var/run/docker.sock
          - name: proc
            mountPath: /host/proc
            readOnly: true
          - name: cgroup
            mountPath: /sys/fs/cgroup
        livenessProbe:
          httpGet:
            path: /v1/plugins
            port: 21413
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /v1/plugins
            port: 21413
          initialDelaySeconds: 5
          timeoutSeconds: 5
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: proc
          hostPath:
            path: /proc
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: swisnap-agent-ds-configmap
          configMap:
            name: swisnap-agent-ds-configmap
